<Project>
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>1.0.11</Version>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
</Project>
